services:
  - type: web
    name: your-app
    env: python
    pythonVersion: "^3.11"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt --only-binary=all
    startCommand: # your start command here
    envVars:
      - key: PIP_ONLY_BINARY
        value: ":all:"
      - key: PIP_NO_BUILD_ISOLATION
        value: "false"